services:
  db:
    image: postgres:16
    container_name: campfire-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: campfire
      POSTGRES_USER: campfire
      POSTGRES_PASSWORD: campfire
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
