# fly.toml app configuration file generated for ruminate-backend on 2025-07-29T23:23:58-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ruminate-backend'
primary_region = 'sjc'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[experimental]
  auto_rollback = true

[build]

[deploy]
  release_command = 'alembic -c new_backend_ruminate/alembic.ini upgrade head'

[env]
  PORT = '8000'
  # Defaults for ingestion + Redis backends (override via fly secrets in prod)
  UPLOAD_PIPELINE_MODE = 'ingestion'
  QUEUE_BACKEND = 'redis'
  EVENT_BACKEND = 'redis'
  # REDIS_URL is set via fly secrets

# Define separate processes for API and worker
[processes]
  app = "uvicorn new_backend_ruminate.main:app --host 0.0.0.0 --port 8000"
  worker = "python -m new_backend_ruminate.worker.processor"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/health'
    protocol = 'http'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
