[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "new_backend_ruminate"
version = "0.0.1"

[tool.setuptools.packages.find]
include = ["new_backend_ruminate*"]
