"""Add chunks table and document_info field

Revision ID: 168dc9a0db77
Revises: 3dc5d1640c2b
Create Date: 2025-08-03 20:48:14.974943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '168dc9a0db77'
down_revision: Union[str, None] = '3dc5d1640c2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create chunks table
    op.create_table('chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('start_page', sa.Integer(), nullable=False),
    sa.Column('end_page', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('processing_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Add chunk_id to blocks table
    op.add_column('blocks', sa.Column('chunk_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'blocks', 'chunks', ['chunk_id'], ['id'])
    
    # Add document_info to documents table
    op.add_column('documents', sa.Column('document_info', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove document_info from documents
    op.drop_column('documents', 'document_info')
    
    # Remove chunk_id from blocks
    op.drop_constraint(None, 'blocks', type_='foreignkey')
    op.drop_column('blocks', 'chunk_id')
    
    # Drop chunks table
    op.drop_table('chunks')
    # ### end Alembic commands ###