"""add active_child_id to messages

Revision ID: 3e199b0b532c
Revises: aa0f8d748149
Create Date: 2025-07-26 21:37:52.418231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e199b0b532c'
down_revision: Union[str, None] = 'aa0f8d748149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('uq_conversation_id', 'conversations', ['id'])  # Already exists
    op.add_column('messages', sa.Column('active_child_id', sa.String(), nullable=True))
    op.create_index('ix_conv_parent', 'messages', ['conversation_id', 'parent_id'], unique=False)
    op.create_index(op.f('ix_messages_active_child_id'), 'messages', ['active_child_id'], unique=False)
    op.create_index('ix_parent_version_desc', 'messages', ['parent_id', sa.text('version DESC')], unique=False)
    op.create_foreign_key(None, 'messages', 'messages', ['active_child_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index('ix_parent_version_desc', table_name='messages')
    op.drop_index(op.f('ix_messages_active_child_id'), table_name='messages')
    op.drop_index('ix_conv_parent', table_name='messages')
    op.drop_column('messages', 'active_child_id')
    op.drop_constraint('uq_conversation_id', 'conversations', type_='unique')
    # ### end Alembic commands ###
