"""initial schema (UUID)

Revision ID: 5b732fce715c
Revises: 
Create Date: 2025-06-22 16:30:23.819485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b732fce715c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('root_message_id', sa.UUID(), nullable=True),
    sa.Column('active_thread_ids', sa.JSON(), nullable=False),
    sa.Column('type', sa.Enum('CHAT', 'AGENT', name='conversationtype'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', name='uq_conversation_id')
    )
    op.create_table('dreams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', 'TOOL', name='role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('active_child_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['active_child_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'version', name='uq_parent_version')
    )
    op.create_index('ix_conv_parent', 'messages', ['conversation_id', 'parent_id'], unique=False)
    op.create_index(op.f('ix_messages_active_child_id'), 'messages', ['active_child_id'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_parent_id'), 'messages', ['parent_id'], unique=False)
    op.create_index('ix_parent_version_desc', 'messages', ['parent_id', sa.text('version DESC')], unique=False)
    op.create_table('segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('dream_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dream_id'], ['dreams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('segments')
    op.drop_index('ix_parent_version_desc', table_name='messages')
    op.drop_index(op.f('ix_messages_parent_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_active_child_id'), table_name='messages')
    op.drop_index('ix_conv_parent', table_name='messages')
    op.drop_table('messages')
    op.drop_table('dreams')
    op.drop_table('conversations')
    # ### end Alembic commands ###
