services:
  db:
    image: postgres:16
    container_name: ruminate-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ruminate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: ruminate-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  pgdata: