from abc import ABC, abstractmethod
from typing import Any, List, Optional
from sqlalchemy.ext.asyncio import AsyncSession
from uuid import UUID

from new_backend_ruminate.domain.dream.entities.dream import Dream
from new_backend_ruminate.domain.dream.entities.audio_segments import AudioSegment

class DreamRepository(ABC):
    # dreams
    @abstractmethod
    async def create_dream(self, dream: Dream, session: AsyncSession) -> Dream: ...
    @abstractmethod
    async def get_dream(self, did: UUID, session: AsyncSession) -> Optional[Dream]: ...
    @abstractmethod
    async def list_dreams_by_user(self, user_id: UUID, session: AsyncSession) -> List[Dream]: ...
    @abstractmethod
    async def update_title(self, user_id: UUID, did: UUID, title: str, session: AsyncSession) -> Optional[Dream]: ...
    @abstractmethod
    async def set_state(self, user_id: UUID, did: UUID, state: str, session: AsyncSession) -> Optional[Dream]: ...
    @abstractmethod
    async def delete_dream(self, user_id: UUID, did: UUID, session: AsyncSession) -> Optional[Dream]: ...

    # segments
    @abstractmethod
    async def create_segment(self, segment: AudioSegment, session: AsyncSession) -> AudioSegment: ...
    @abstractmethod
    async def get_segment(self, did: UUID, sid: UUID, session: AsyncSession) -> Optional[AudioSegment]: ...
    @abstractmethod
    async def delete_segment(self, did: UUID, sid: UUID, session: AsyncSession) -> Optional[AudioSegment]: ...
    @abstractmethod
    async def update_segment_transcript(self, did: UUID, sid: UUID, transcript: str, session: AsyncSession) -> Optional[AudioSegment]: ...
    
    # getters
    @abstractmethod
    async def get_video_url(self, did: UUID, session: AsyncSession) -> Optional[str]: ...
    @abstractmethod
    async def get_transcript(self, did: UUID, session: AsyncSession) -> Optional[str]: ...
    @abstractmethod
    async def get_audio_url(self, did: UUID, session: AsyncSession) -> Optional[str]: ...
    @abstractmethod
    async def get_status(self, did: UUID, session: AsyncSession) -> Optional[str]: ...